package hooks

// TypeScriptTypes returns TypeScript declaration strings for claude-hooks
// script authors. The content mirrors the Go types in input.go and decision.go.
func TypeScriptTypes() string {
	return `// claude-hooks TypeScript type definitions
// Auto-generated by: claude-hooks gen-types
// Do not edit manually.

export interface HookInput {
  /** Name of the hook event, e.g. "PreToolUse" */
  hook_event_name: string;
  /** Claude session identifier */
  session_id: string;
  /** Path to the transcript file */
  transcript_path: string;
  /** Current working directory */
  cwd: string;
  /** Permission mode active in this session */
  permission_mode: string;
  /** Tool being called (PreToolUse / PostToolUse only) */
  tool_name?: string;
  /** Raw tool input arguments */
  tool_input?: Record<string, unknown>;
  /** Tool use call identifier */
  tool_use_id?: string;
  /** Serialized result from the tool (PostToolUse only) */
  tool_result?: string;
  /** Any extra fields not yet in the schema */
  [key: string]: unknown;
}

/** Deny the PreToolUse tool call */
export interface DenyOutput {
  hookSpecificOutput: {
    permissionDecision: "deny";
    permissionDecisionReason?: string;
  };
}

/** Explicitly allow the PreToolUse tool call (no input rewriting) */
export interface AllowOutput {
  hookSpecificOutput: {
    permissionDecision: "allow";
  };
}

/** Allow the PreToolUse call and rewrite the tool input before execution */
export interface AllowWithUpdatedInputOutput {
  hookSpecificOutput: {
    permissionDecision: "allow";
    /** Partial or full replacement for the tool's input fields */
    updatedInput?: Record<string, unknown>;
  };
}

/** Forward to Claude Code's built-in permission dialog */
export interface AskOutput {
  hookSpecificOutput: {
    permissionDecision: "ask";
    permissionDecisionReason?: string;
  };
}

/** Block Claude after PostToolUse / Stop */
export interface BlockOutput {
  hookSpecificOutput: {
    decision: "block";
    reason?: string;
    additionalContext?: string;
  };
}

/** Stop all Claude activity immediately */
export interface GlobalStopOutput {
  continue: false;
  stopReason: string;
}

/** No opinion — Claude continues its normal flow (return null or undefined) */
export type DeferOutput = null | undefined;

export type HookOutput =
  | DenyOutput
  | AllowWithUpdatedInputOutput
  | AskOutput
  | BlockOutput
  | GlobalStopOutput
  | DeferOutput;

/** Type of a script rule handler function */
export type RuleHandler = (input: HookInput) => HookOutput | Promise<HookOutput>;
`
}
